

rococo-front:
    base-uri: 'http://127.0.0.1:3000'
rococo-auth:
    base-uri: 'http://127.0.0.1:9000'
oauth2:
    client-id: 'client'
    client-secret: '{noop}secret'

spring:
    datasource:
        url: 'jdbc:mysql://localhost:3306/rococo'
        username: admin
        password: admin
    flyway:
        enabled: true
        baseline-on-migrate: true
        baseline-version: 0
        locations: classpath:migration/auth-init
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: false
        generate-ddl: true
        open-in-view: false

server:
    port: 9000


grpc:
    server:
        port: 8094
