

rococo-front:
    base-uri: 'http://127.0.0.1:3000'
rococo-auth:
    base-uri: 'http://127.0.0.1:9000'
oauth2:
    client-id: 'client'
    client-secret: '{noop}secret'

spring:
    datasource:
        url: 'jdbc:mysql://localhost:3306/rococo'
        username: admin
        password: admin

server:
    port: 8086